
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jorge Eduardo Escobar Bugarini
 */
public class Window extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSumatoriaFor = new javax.swing.JButton();
        btnSumatoriaDoWhile = new javax.swing.JButton();
        btnSumatoriaWhile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 204, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setText("Sumatoria");

        btnSumatoriaFor.setBackground(new java.awt.Color(51, 51, 51));
        btnSumatoriaFor.setForeground(new java.awt.Color(255, 255, 255));
        btnSumatoriaFor.setText("Sumatoria For");
        btnSumatoriaFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoriaForActionPerformed(evt);
            }
        });

        btnSumatoriaDoWhile.setBackground(new java.awt.Color(51, 51, 51));
        btnSumatoriaDoWhile.setForeground(new java.awt.Color(255, 255, 255));
        btnSumatoriaDoWhile.setText("Sumatoria  do while");
        btnSumatoriaDoWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoriaDoWhileActionPerformed(evt);
            }
        });

        btnSumatoriaWhile.setBackground(new java.awt.Color(51, 51, 51));
        btnSumatoriaWhile.setForeground(new java.awt.Color(255, 255, 255));
        btnSumatoriaWhile.setText("Sumatoria while");
        btnSumatoriaWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoriaWhileActionPerformed(evt);
            }
        });

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblTitle)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSumatoriaDoWhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSumatoriaWhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSumatoriaFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSumatoriaDoWhile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSumatoriaWhile)
                        .addGap(18, 18, 18)
                        .addComponent(btnSumatoriaFor)
                        .addGap(86, 86, 86))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnSumatoriaForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaForActionPerformed
        int n = Integer.parseInt(JOptionPane.showInputDialog(null,"Introduce un numero hasta el cual haras la sumatoria"));
        int s=0;
        for(int i=1; i<=n; i++) s+=i;
        txtSalida.setText("La sumatoria de 1 hasta "+n+" es: "+s);
    }//GEN-LAST:event_btnSumatoriaForActionPerformed

    private void btnSumatoriaDoWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaDoWhileActionPerformed
        int n = Integer.parseInt(JOptionPane.showInputDialog(null,"Introduce un numero hasta el cual haras la sumatoria"));
        int s=0, i=n;
        do{
            s+=i;
            i--;
        }while(i>=1);
        txtSalida.setText("La sumatoria de 1 hasta "+n+" es: "+s);
    }//GEN-LAST:event_btnSumatoriaDoWhileActionPerformed

    private void btnSumatoriaWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaWhileActionPerformed
        
        int n = Integer.parseInt(JOptionPane.showInputDialog(null,"Introduce un numero hasta el cual haras la sumatoria"));
        int s=0,i=n;
        while(i>=1){
            s+=i;
            i--;
        }              
        txtSalida.setText("La sumatoria de 1 hasta "+n+" es: "+s);
    }//GEN-LAST:event_btnSumatoriaWhileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSumatoriaDoWhile;
    private javax.swing.JButton btnSumatoriaFor;
    private javax.swing.JButton btnSumatoriaWhile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
