/**
 *
 * @autor Jorge Eduardo Escobar Bugarini
 * @carrera Ingenieria en Sistemas Computacionales
 * @materia Fundamentos de Programacion 9-10
 */
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class Window extends java.awt.Frame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalificaciones = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        btnCalificaciones.setBackground(new java.awt.Color(0, 204, 204));
        btnCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setText("Capturar y Datos");
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setText("Calificaciones Visual");

        lblName.setForeground(new java.awt.Color(51, 51, 51));
        lblName.setText("Jorge Eduardo Escobar Bugarini ISC FP-9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(lblName)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    private static void capturar(int numCalif, double calif[]){
          for(int  i=0; i<numCalif; i++){
            calif[i]=Double.parseDouble(JOptionPane.showInputDialog(null,"Introduce la calificacion Num. "+(i+1)));
        }
    }
    private static double promedio(int numCalif, double calif[]){
        double promedio, sumatoria=0.0;
        for(int i=0; i<numCalif; i++){
            sumatoria+=calif[i];
        }
        promedio=sumatoria/numCalif;
        return promedio;
    }
    private static double mayor(int numCalif, double calif[]){
        double mayor=calif[0];
        for(int i=0; i<numCalif; i++){
            if(calif[i]>mayor) mayor=calif[i];
        }
        return mayor;
    }
    private static double menor(int numCalif, double calif[]){
        double menor=calif[0];
        for(int i=0; i<numCalif; i++){
            if(calif[i]<menor) menor=calif[i];
        }
        return menor;
    }
    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        int n = Integer.parseInt(JOptionPane.showInputDialog(null,"Escribe el numero de calificaciones a capturar (Maximo 40)"));
        if(n>40){
            JOptionPane.showMessageDialog(null, "Limite de calificaciones excedido, se capturaran 40 calificaciones", "Advertencia", JOptionPane.WARNING_MESSAGE);
            n=40;
        }
        if(n<=0){
            JOptionPane.showConfirmDialog(null, "No se capturaron calificaciones", "Advertencia", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
        double calificaciones[] = new double[n];
        capturar(n,calificaciones);
        DecimalFormat df = new DecimalFormat("0.00");

        String salida = "El promedio de las "+n+" calificaciones es: "+df.format(promedio(n, calificaciones))+"\n";
        salida+="La mayor de las "+n+" calificaciones es: "+df.format(mayor(n, calificaciones))+"\n";
        salida+="La menor de las "+n+" calificaciones es: "+df.format(menor(n, calificaciones));

        JOptionPane.showMessageDialog(null,salida);

    }//GEN-LAST:event_btnCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificaciones;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
