import javax.swing.JOptionPane;

/**
 * @autores: Jorge Eduardo Escobar Bugarini
 *                     Rocio Vanesa Gardea Hernandez
 *                      Diego Gael Martin del Campo
 *                      Julio Eduardo Rascon Vega
 *                      Jesus Alejandro Torres Ramirez
 */
public class cajaRegistradora extends java.awt.Frame {
    int total=0;
    String compras="";
    /** Creates new form cajaRegistradora */
    public cajaRegistradora() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btnArticulos = new java.awt.Button();
        btnMejor = new java.awt.Button();
        btnCarrito = new java.awt.Button();
        btnDescuentos = new java.awt.Button();
        txaSalida = new java.awt.TextArea();
        label2 = new java.awt.Label();

        setBackground(new java.awt.Color(255, 255, 51));
        setPreferredSize(new java.awt.Dimension(900, 720));
        setSize(new java.awt.Dimension(900, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Niagara Engraved", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 255));
        label1.setText("¡Bienvenido a Gensokyo!");

        btnArticulos.setBackground(new java.awt.Color(0, 51, 255));
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setLabel("Nuestros artículos.");
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });

        btnMejor.setBackground(new java.awt.Color(0, 51, 255));
        btnMejor.setForeground(new java.awt.Color(255, 255, 255));
        btnMejor.setLabel("¿Qué es mejor para ti?");
        btnMejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorActionPerformed(evt);
            }
        });

        btnCarrito.setBackground(new java.awt.Color(0, 51, 255));
        btnCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrito.setLabel("Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnDescuentos.setBackground(new java.awt.Color(0, 51, 255));
        btnDescuentos.setForeground(new java.awt.Color(255, 255, 255));
        btnDescuentos.setLabel("Descuentos");
        btnDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentosActionPerformed(evt);
            }
        });

        txaSalida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 51, 255));
        label2.setText("Gracias por visitarnos, vuelva pronto.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(txaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // Los articulos que tenemos en existencia
        String articulos = "\t\t\t\tARTICULOS DISPONIBLES\n";
        articulos+="Memoria RAM HyperX 2x8 GB DDR4 2666MHz - $1750.00\n";
        articulos+="Memoria RAM Corsair Vengeance 2x8 GB DDR4 2666MHz - $1940.00\n";
        articulos+="Procesador Intel Core i7 12700K, 5.00 GHz 8 núcleos S-1700 - $10329.00\n";
        articulos+="Procesador Intel Core i5 12600K, 4.90 GHz 8 núcleos S-1700 - $7250.00\n";
        articulos+="Asus Tarjeta Madre B660 Intel, Prime B660-PLUS D4, LGA 1700 ATX - $3450.00\n";
        articulos+="Asus Tarjeta Madre Z690 Intel, Prime Z690M-PLUS D4, mATX PCIe 5.0 - $4670.00\n";
        articulos+="Tarjeta de video Radeon RX 6600 XT 8GB GDDR6 / Power Color HELLHOUND - $14999.00\n";
        articulos+="Tarjeta de Video Nvidia GeForce RTX 3060 / ZOTAC TWIN EDGE LHR - $15999.00";
        txaSalida.setText(articulos);
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnMejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorActionPerformed
        // Comparacion de cual tiene el precio menor de los dos artículos
        String mejores="\t\t\t\tMEJORES ARTICULOS\n";
        mejores+="Memoria RAM HyperX 2x8 GB DDR4 2666MHz - $1750.00\n";
        mejores+="Procesador Intel Core i5 12600K, 4.90 GHz 8 núcleos S-1700 - $7250.00\n";
        mejores+="Asus Tarjeta Madre B660 Intel, Prime B660-PLUS D4, LGA 1700 ATX - $3450.00\n";
        mejores+="Tarjeta de video Radeon RX 6600 XT 8GB GDDR6 / Power Color HELLHOUND - $14999.00\n";
        txaSalida.setText(mejores);
    }//GEN-LAST:event_btnMejorActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // Suma de todos los articulos que desea adquirir
        
        String menu = "****MENU DE COMPRA****\n";
        menu+="Introduce el numero del articulo u opcion que deseas seleccionar\n";
        menu += "1.- Memoria RAM HyperX 2x8 GB DDR4 2666MHz - $1750.00\n";
        menu += "2.- Memoria RAM Corsair Vengeance 2x8 GB DDR4 2666MHz - $1940.00\n";
        menu += "3.- Procesador Intel Core i7 12700K, 5.00 GHz 8 núcleos S-1700 - $10329.00\n";
        menu += "4.- Procesador Intel Core i5 12600K, 4.90 GHz 8 núcleos S-1700 - $7250.00\n";
        menu += "5.- Asus Tarjeta Madre B660 Intel, Prime B660-PLUS D4, LGA 1700 ATX - $3450.00\n";
        menu += "6.- Asus Tarjeta Madre Z690 Intel, Prime Z690M-PLUS D4, mATX PCIe 5.0 - $4670.00\n";
        menu += "7.- Tarjeta de video Radeon RX 6600 XT 8GB GDDR6 / Power Color HELLHOUND - $14999.00\n";
        menu += "8.- Tarjeta de Video Nvidia GeForce RTX 3060 / ZOTAC TWIN EDGE LHR - $15999.00\n";
        menu += "9.- Vaciar carrito\n";
        menu += "10.- Salir";
        int opcion,cProductos;
        String producto="";
        do{
            int precio;
            opcion = Integer.parseInt(JOptionPane.showInputDialog(null,menu, "MENU DE COMPRA", JOptionPane.INFORMATION_MESSAGE));
            switch(opcion){
                case 1:
                    precio=1750;
                    producto="Memoria RAM HyperX 2x8 GB DDR4 2666MHz\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    
                    break;
                case 2:
                    precio=1940;
                    producto="Memoria RAM Corsair Vengeance 2x8 GB DDR4 2666MHz\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");      
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 3:
                    precio=10329;
                    producto="Procesador Intel Core i7 12700K, 5.00 GHz 8 núcleos S-1700\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");  
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 4:
                    precio=7250;
                    producto="Procesador Intel Core i5 12600K, 4.90 GHz 8 núcleos S-1700\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");  
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 5:
                    precio=3450;
                    producto="Asus Tarjeta Madre B660 Intel, Prime B660-PLUS D4, LGA 1700 ATX\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");  
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 6:
                    precio=4670;
                    producto="Asus Tarjeta Madre Z690 Intel, Prime Z690M-PLUS D4, mATX PCIe 5.0\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");  
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 7:
                    precio=14999;
                    producto="Tarjeta de video Radeon RX 6600 XT 8GB GDDR6 / Power Color HELLHOUND\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos");  
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;
                case 8:
                    precio=15999;
                    producto="Tarjeta de Video Nvidia GeForce RTX 3060 / ZOTAC TWIN EDGE LHR\n";
                    cProductos=Integer.parseInt(JOptionPane.showInputDialog(this, "Vas a agregar el producto:\n"+producto+"Por un precio de "+precio+"\n¿Cuantos"
                            + " productos deseas añadir de este tipo?"));
                    if(cProductos>0){
                        total+=precio*cProductos;
                        compras+=cProductos+" x "+producto+"\n";
                        JOptionPane.showMessageDialog(null,"Productos añadidos"); 
                    }else JOptionPane.showMessageDialog(null,"No se añadieron productos");
                    break;    
                case 9:
                    total=0;
                    compras="";
                   JOptionPane.showMessageDialog(null,"Carrito vaciado"); 
                    break;
                case 10:
                    break;
                default:
                    JOptionPane.showMessageDialog(null,"Selecciona una opcion valida.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }while(opcion!=10);
        if(!compras.equals("")) txaSalida.setText(compras+"\nTotal: $"+total);
        else txaSalida.setText("No fueron añadidos productos");
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentosActionPerformed
        // Por cada monto de compra establecido habrá un descuento del 15 porciento de su compra
        if(total>=5000){
            txaSalida.setText("Ya que su compra es mayor a $5000 se le aplicara un 15% de descuento\nUsted pagara: "+(total*0.85));
        }else txaSalida.setText("Su compra no es valida para descuento");
    }//GEN-LAST:event_btnDescuentosActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cajaRegistradora().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnArticulos;
    private java.awt.Button btnCarrito;
    private java.awt.Button btnDescuentos;
    private java.awt.Button btnMejor;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextArea txaSalida;
    // End of variables declaration//GEN-END:variables

}
