import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jorge Eduardo Escobar Bugarini
 */
public class Window extends java.awt.Frame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnProblema1 = new javax.swing.JButton();
        btnProblema2 = new javax.swing.JButton();
        btnProblema3 = new javax.swing.JButton();
        authorName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(600, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 480));
        setTitle("Proyecto Condiciones");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        title.setBackground(new java.awt.Color(51, 51, 51));
        title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Proyecto Condiciones");

        btnProblema1.setBackground(new java.awt.Color(0, 153, 153));
        btnProblema1.setForeground(new java.awt.Color(255, 255, 255));
        btnProblema1.setText("Problema A");
        btnProblema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProblema1ActionPerformed(evt);
            }
        });

        btnProblema2.setBackground(new java.awt.Color(0, 153, 153));
        btnProblema2.setForeground(new java.awt.Color(255, 255, 255));
        btnProblema2.setText("Problema B");
        btnProblema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProblema2ActionPerformed(evt);
            }
        });

        btnProblema3.setBackground(new java.awt.Color(0, 153, 153));
        btnProblema3.setForeground(new java.awt.Color(255, 255, 255));
        btnProblema3.setText("Problema C");
        btnProblema3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProblema3ActionPerformed(evt);
            }
        });

        authorName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        authorName.setForeground(new java.awt.Color(51, 51, 51));
        authorName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorName.setText("Jorge Eduardo Escobar Bugarini ISC-FP-9");

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProblema1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnProblema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProblema3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(authorName, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnProblema1)
                        .addGap(18, 18, 18)
                        .addComponent(btnProblema2)
                        .addGap(18, 18, 18)
                        .addComponent(btnProblema3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(authorName)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnProblema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProblema1ActionPerformed
        int compra = Integer.parseInt(JOptionPane.showInputDialog(null,"¿Cuál fue el monto de tu compra?"));
        String salida="";
        if(compra>=1100){
            int boletos=(compra-1000)/100;
            salida = "Obtienes "+boletos+" boletos\n";
        }
        this.salida.setText(salida+"Gracias por tu compra");
    }//GEN-LAST:event_btnProblema1ActionPerformed

    private void btnProblema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProblema2ActionPerformed
        int numero  = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduce un numero"));
        if(numero%2==0) salida.setText("El numero "+numero+ " es par");
        else salida.setText("El numero "+numero+ " es impar");
    }//GEN-LAST:event_btnProblema2ActionPerformed

    private void btnProblema3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProblema3ActionPerformed
        int dia = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduce un dia del 1 al 7"));
        switch(dia){
            case 1:
                salida.setText("Domingo");
            break;
            case 2:
                salida.setText("Lunes");
            break;
            case 3:
                salida.setText("Martes");
            break;
            case 4:
                salida.setText("Miercoles");
            break;
            case 5:
                salida.setText("Jueves"); 
            break;
            case 6:
                salida.setText("Viernes");
            break;
            case 7:
                salida.setText("Sabado");
            break;                
            default:
                salida.setText("Dia invalido");
        }
    }//GEN-LAST:event_btnProblema3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorName;
    private javax.swing.JButton btnProblema1;
    private javax.swing.JButton btnProblema2;
    private javax.swing.JButton btnProblema3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea salida;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
